#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World inside

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
	location / {
                try_files \$uri \$uri/ =404;
        }

        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"

echo "$new_config" > /etc/nginx/sites-available/default

sudo service nginx start
