#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World inside

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites-available/default

sudo service nginx start
