#!/usr/bin/env bash
# Configure Nginx server to give error 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

string_rep="server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	error_page 404 /404.html;
	location  /404.html {
		internal;
	}\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGU1wu4 permanent;
"
echo "Ceci n'est pas une page" > sudo var/www/html/404.html

sudo sed -i "s/server_name _;/$string_rep/" /etc/nginx/sites-enabled/default

sudo service nginx restart
