#!/usr/bin/env bash
# Configure Nginx server to give error 404 page
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_rep="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_rep/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo var/www/html/404.html

string_rep="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_rep/" /etc/nginx/sites-enabled/default


sudo service nginx restart
